version: '2'
services:
  saibdigitalwallet-app:
    image: saibdigitalwallet
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://saibdigitalwallet-mssql:1433;database=SAIBDigitalWallet
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://saibdigitalwallet-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://saibdigitalwallet-elasticsearch:9200
    ports:
      - 8080:8080
  saibdigitalwallet-mssql:
    extends:
      file: mssql.yml
      service: saibdigitalwallet-mssql
  saibdigitalwallet-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: saibdigitalwallet-elasticsearch
